[package]
name = "redis-async"
version = "0.6.1"
authors = ["Ben Ashford <benashford@users.noreply.github.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "An asynchronous futures based Redis client for Rust using Tokio"
repository = "https://github.com/benashford/redis-async-rs"
keywords = ["redis", "tokio"]
edition = "2018"

[dependencies]
bytes = "^1.0.1"
log = "^0.4.14"
futures-channel = "^0.3.13"
futures-sink = "^0.3.13"
futures-util = "^0.3.13"
tokio = { version = "^1.4.0", features = ["full"] }
tokio-util = { version = "^0.6.5", features = ["codec"] }

[dev-dependencies]
env_logger = "^0.8.3"
futures = "^0.3.13"
tokio = { version = "^1.4.0", features = ["full"] }
